export interface SpecialtyItem {
  id: string;
  title: string;
  category: 'Cardiac' | 'Oncology' | 'Transplant' | 'Neuro' | 'Orthopedics' | 'Fertility' | 'Pediatrics' | 'Specialized';
  shortDesc: string;
  fullDesc: string;
  commonProcedures: string[];
  costFrom: string;
  savingsPercentage: string;
  featuredHospitals: string[];
  iconName: string;
}

export const allSpecialties: SpecialtyItem[] = [
  {
    id: 'cardiac-surgery',
    title: 'Cardiac Sciences & Heart Surgery',
    category: 'Cardiac',
    shortDesc: 'World-leading heart institutes with 99.6% surgical success rates for adult and pediatric cardiac surgery.',
    fullDesc: 'Comprehensive cardiac sciences encompassing beating-heart coronary artery bypass graft (CABG), minimally invasive valve repair/replacement (TAVI/TAVR), robotic cardiac revascularization, and complex congenital heart defects correction.',
    commonProcedures: ['CABG (Heart Bypass)', 'Valve Replacement (TAVI)', 'Angioplasty & Stenting', 'Pediatric Heart Surgery', 'Robotic Cardiac Surgery'],
    costFrom: '$4,800',
    savingsPercentage: '75%',
    featuredHospitals: ['Medanta Hospital, Gurugram', 'Apollo Hospitals India', 'Fortis Healthcare India'],
    iconName: 'Heart',
  },
  {
    id: 'oncology-cancer-care',
    title: 'Comprehensive Oncology & CAR-T',
    category: 'Oncology',
    shortDesc: 'Next-generation cancer treatments including CAR T-cell therapy, CyberKnife, and Proton Beam therapy.',
    fullDesc: 'State-of-the-art precision oncology delivering South Asia’s first Proton Beam therapy, indigenous CAR T-cell therapy (NexCAR19), robotic TrueBeam radiosurgery, targeted immunotherapy, and multi-specialty tumor board deliberations.',
    commonProcedures: ['CAR T-cell Therapy', 'Proton Beam Therapy', 'CyberKnife Radiosurgery', 'Surgical Oncology', 'Targeted Immunotherapy'],
    costFrom: '$3,500',
    savingsPercentage: '80%',
    featuredHospitals: ['Max Healthcare, Delhi', 'Apollo Hospitals India', 'HCG Cancer Centre, Bangalore'],
    iconName: 'Sparkles',
  },
  {
    id: 'organ-transplant',
    title: 'Solid Organ Transplantation',
    category: 'Transplant',
    shortDesc: 'Pioneering living-donor liver, kidney, heart, and lung transplants with world-class survival outcomes.',
    fullDesc: 'India is internationally recognized as the world hub for living-donor liver and kidney transplantation, delivering thousands of successful transplants annually with dedicated high-dependency isolation ICUs and strict regulatory approvals.',
    commonProcedures: ['Living-Donor Liver Transplant', 'Kidney (Renal) Transplant', 'Heart & Lung Transplant', 'Pediatric Liver Transplant', 'ABO-Incompatible Transplant'],
    costFrom: '$12,000',
    savingsPercentage: '75%',
    featuredHospitals: ['Gleneagles Global Health City, Chennai', 'Medanta Hospital, Gurugram', 'Fortis Healthcare India'],
    iconName: 'Activity',
  },
  {
    id: 'bone-marrow-transplant',
    title: 'Bone Marrow & Stem Cell Transplant (BMT)',
    category: 'Transplant',
    shortDesc: 'HEPA-filtered sterile BMT suites for leukemia, lymphoma, thalassemia, and severe aplastic anemia.',
    fullDesc: 'Quaternary hematology programs performing autologous, allogeneic, and haploidentical (half-matched) bone marrow transplants backed by in-house stem-cell processing laboratories and zero-infection containment rooms.',
    commonProcedures: ['Allogeneic BMT', 'Autologous Stem Cell Transplant', 'Haploidentical BMT', 'Thalassemia BMT', 'Multiple Myeloma Protocol'],
    costFrom: '$15,000',
    savingsPercentage: '80%',
    featuredHospitals: ['Fortis Healthcare India', 'Artemis Hospital, Gurugram', 'Max Healthcare, Delhi'],
    iconName: 'Dna',
  },
  {
    id: 'orthopedics-joint-spine',
    title: 'Orthopaedics, Robotic Joints & Spine',
    category: 'Orthopedics',
    shortDesc: 'Robotic knee and hip arthroplasty, complex scoliosis correction, and minimally invasive spine surgery.',
    fullDesc: 'Pioneering orthopaedic centers utilizing robotic arm navigation (MAKO, Rosa) for sub-millimeter precision joint replacements, sports medicine arthroscopy, endoscopic disc surgery, and dynamic spine stabilization.',
    commonProcedures: ['Robotic Total Knee Replacement', 'Total Hip Replacement', 'Minimally Invasive Spine (MISS)', 'Scoliosis Deformity Correction', 'ACL / Arthroscopy'],
    costFrom: '$4,200',
    savingsPercentage: '70%',
    featuredHospitals: ['Artemis Hospital, Gurugram', 'Kokilaben Hospital, Mumbai', 'Apollo Hospitals India'],
    iconName: 'Bone',
  },
  {
    id: 'neurology-neurosurgery',
    title: 'Neurosciences & Robotic Neurosurgery',
    category: 'Neuro',
    shortDesc: 'Intra-operative 3T MRI, brain tumor resection, deep brain stimulation (DBS), and neuro-rehabilitation.',
    fullDesc: 'Dedicated neurosurgical suites equipped with neuronavigation, intraoperative neuro-monitoring (IONM), gamma knife radiosurgery, endovascular coiling for aneurysms, and comprehensive post-stroke rehabilitation centers.',
    commonProcedures: ['Brain Tumor Resection (Craniotomy)', 'Deep Brain Stimulation (DBS)', 'Brain Aneurysm Coiling', 'Robotic Spine Surgery', 'Epilepsy Surgery'],
    costFrom: '$5,500',
    savingsPercentage: '75%',
    featuredHospitals: ['Kokilaben Hospital, Mumbai', 'Gleneagles Global Health City, Chennai', 'Wockhardt Hospitals, Mumbai'],
    iconName: 'Brain',
  },
  {
    id: 'fertility-ivf',
    title: 'Reproductive Medicine, IVF & Fertility',
    category: 'Fertility',
    shortDesc: 'High success-rate IVF, ICSI, and pre-implantation genetic screening (PGT-A/M) at specialized institutes.',
    fullDesc: 'State-of-the-art embryology cleanrooms offering customized IVF stimulation protocols, intracytoplasmic sperm injection (ICSI), blastocyst culture, egg cryopreservation, and genetic screening for chromosomal abnormalities.',
    commonProcedures: ['IVF with ICSI Cycle', 'PGT-A Genetic Screening', 'Blastocyst Embryo Transfer', 'Egg & Embryo Freezing', 'Male Infertility (PESA/TESA)'],
    costFrom: '$2,800',
    savingsPercentage: '65%',
    featuredHospitals: ['Rainbow Children\'s Hospital & BirthRight', 'Fortis Healthcare India', 'Max Healthcare, Delhi'],
    iconName: 'Baby',
  },
  {
    id: 'pediatrics-neonatology',
    title: 'Advanced Paediatrics & Neonatology',
    category: 'Pediatrics',
    shortDesc: 'Level-3B NICU and dedicated pediatric super-specialties for complex congenital disorders.',
    fullDesc: 'India’s foremost pediatric tertiary ecosystems designed exclusively for infants and children, encompassing neonatal intensive care, pediatric cardiac surgery, pediatric organ transplants, and neurodevelopmental therapies.',
    commonProcedures: ['Level-III NICU Care', 'Pediatric Cardiac Surgery (VSD/TOF)', 'Pediatric Liver Transplant', 'Cleft Lip & Palate Correction', 'Pediatric Neurosurgery'],
    costFrom: '$3,800',
    savingsPercentage: '70%',
    featuredHospitals: ['Rainbow Children\'s Hospital and BirthRight, Hyderabad', 'Medanta Hospital, Gurugram', 'Artemis Hospital, Gurugram'],
    iconName: 'Shield',
  },
  {
    id: 'gastroenterology-bariatric',
    title: 'Gastroenterology, Hepatology & Bariatrics',
    category: 'Specialized',
    shortDesc: 'Advanced therapeutic endoscopy, comprehensive liver disease care, and metabolic weight-loss surgery.',
    fullDesc: 'Complete digestive disease institutes covering third-space endoscopy (POEM, ESD), endoscopic retrograde cholangiopancreatography (ERCP), fatty liver/cirrhosis management, and laparoscopic bariatric surgery for metabolic health.',
    commonProcedures: ['Laparoscopic Gastric Bypass', 'Sleeve Gastrectomy', 'Therapeutic ERCP', 'Endoscopic Mucosal Resection', 'Liver Cirrhosis Care'],
    costFrom: '$3,900',
    savingsPercentage: '70%',
    featuredHospitals: ['Wockhardt Hospitals, Mumbai', 'Gleneagles Global Health City, Chennai', 'Medanta Hospital, Gurugram'],
    iconName: 'Stethoscope',
  },
  {
    id: 'nephrology-urology',
    title: 'Nephrology, Dialysis & Robotic Urology',
    category: 'Specialized',
    shortDesc: 'Da Vinci robotic prostatectomies, laser stone vaporization, and chronic kidney disease management.',
    fullDesc: 'Integrated kidney and urinary science departments featuring Holmium laser enucleation of the prostate (HoLEP), flexible ureteroscopy (RIRS) for renal calculi, robotic partial nephrectomy, and maintenance hemodialysis.',
    commonProcedures: ['Robotic Prostatectomy', 'Laser Kidney Stone Removal (RIRS)', 'Hemodialysis Packages', 'Bladder Tumor Resection (TURBT)', 'Reconstructive Urology'],
    costFrom: '$2,500',
    savingsPercentage: '70%',
    featuredHospitals: ['Fortis Healthcare India', 'Apollo Hospitals India', 'Kokilaben Hospital, Mumbai'],
    iconName: 'Droplets',
  },
  {
    id: 'ophthalmology-eye-surgery',
    title: 'Advanced Ophthalmology & Eye Surgery',
    category: 'Specialized',
    shortDesc: 'Blade-free robotic SMILE laser vision correction, complex corneal grafts, and vitreoretinal surgery.',
    fullDesc: 'Accredited eye care centers equipped with femtosecond laser cataract platforms, trifocal intraocular lens implants, keratoconus cross-linking, and micro-incision vitrectomy surgery for diabetic retinopathy and retinal detachment.',
    commonProcedures: ['Femto-LASIK / SMILE Eye Surgery', 'Robotic Cataract with Multifocal IOL', 'Corneal Transplantation', 'Vitreoretinal Surgery', 'Glaucoma Shunt Surgery'],
    costFrom: '$1,200',
    savingsPercentage: '75%',
    featuredHospitals: ['Apollo Hospitals India', 'Medanta Hospital, Gurugram', 'Fortis Healthcare India'],
    iconName: 'Eye',
  },
  {
    id: 'cosmetic-plastic-surgery',
    title: 'Cosmetic, Plastic & Reconstructive Surgery',
    category: 'Specialized',
    shortDesc: 'Aesthetic body contouring, facial rejuvenation, and microvascular reconstructive procedures.',
    fullDesc: 'Board-certified plastic and reconstructive surgeons performing high-definition liposuction, mommy makeovers, advanced rhinoplasty, post-burn microvascular flap reconstruction, and gender confirmation surgeries in accredited hospital suites.',
    commonProcedures: ['High-Definition Liposuction', 'Rhinoplasty (Nose Reshaping)', 'Breast Reconstruction / Augmentation', 'Tummy Tuck (Abdominoplasty)', 'Microvascular Flap Surgery'],
    costFrom: '$2,200',
    savingsPercentage: '75%',
    featuredHospitals: ['Kokilaben Hospital, Mumbai', 'Wockhardt Hospitals, Mumbai', 'Artemis Hospital, Gurugram'],
    iconName: 'Sparkles',
  },
  {
    id: 'dental-maxillofacial',
    title: 'Dental Implants & Maxillofacial Surgery',
    category: 'Specialized',
    shortDesc: 'Full-mouth All-on-4/6 dental implants, orthognathic corrective jaw surgery, and smile makeovers.',
    fullDesc: 'Hospital-backed dental institutes providing immediate-load titanium dental implants, digital 3D guided surgical placement, corrective jaw realignment for bite disorders, and comprehensive aesthetic ceramic restorations.',
    commonProcedures: ['All-on-4 / All-on-6 Dental Implants', 'Single Tooth Immediate Implant', 'Orthognathic Jaw Surgery', 'Full Mouth Rehabilitation', 'Zirconia Crowns & Veneers'],
    costFrom: '$800',
    savingsPercentage: '80%',
    featuredHospitals: ['Apollo Hospitals India', 'Medanta Hospital, Gurugram', 'Fortis Healthcare India'],
    iconName: 'Smile',
  },
  {
    id: 'executive-health-checkup',
    title: 'Executive Health Screening & Diagnostics',
    category: 'Specialized',
    shortDesc: 'Same-day 3T MRI, whole-body PET-CT, genetic disease risk profiling, and executive wellness suites.',
    fullDesc: 'Comprehensive preventive medical evaluations completed within 6 to 8 hours with dedicated VIP international coordinators, advanced 512-slice CT coronary angiograms, cancer tumor marker panels, and lifestyle consultations.',
    commonProcedures: ['Comprehensive Whole-Body Checkup', 'Executive Cardiac Risk Profiling', 'Cancer Screening (Whole-Body PET/CT)', 'Genetic Predisposition Panel', 'Advanced Women’s Wellness'],
    costFrom: '$350',
    savingsPercentage: '85%',
    featuredHospitals: ['Medanta Hospital, Gurugram', 'Apollo Hospitals India', 'Max Healthcare, Delhi'],
    iconName: 'Scan',
  },
];

export interface CostComparisonItem {
  procedure: string;
  category: string;
  india: string;
  singapore: string;
  malaysia: string;
  thailand: string;
  usa: string;
  savings: string;
}

export const expandedCostComparisons: CostComparisonItem[] = [
  {
    procedure: 'CABG (Heart Bypass)',
    category: 'Cardiac',
    india: '$5,200',
    singapore: '$42,000',
    malaysia: '$16,000',
    thailand: '$18,000',
    usa: '$120,000',
    savings: '75% – 90%',
  },
  {
    procedure: 'Living-Donor Liver Transplant',
    category: 'Transplant',
    india: '$28,000',
    singapore: '$220,000',
    malaysia: '$85,000',
    thailand: '$110,000',
    usa: '$400,000',
    savings: '70% – 90%',
  },
  {
    procedure: 'Kidney Transplant',
    category: 'Transplant',
    india: '$12,500',
    singapore: '$85,000',
    malaysia: '$35,000',
    thailand: '$42,000',
    usa: '$280,000',
    savings: '70% – 92%',
  },
  {
    procedure: 'Bone Marrow Transplant (Allogeneic)',
    category: 'Transplant',
    india: '$20,000',
    singapore: '$140,000',
    malaysia: '$60,000',
    thailand: '$75,000',
    usa: '$350,000',
    savings: '75% – 92%',
  },
  {
    procedure: 'Robotic Knee Replacement (Unilateral)',
    category: 'Orthopedics',
    india: '$4,200',
    singapore: '$26,000',
    malaysia: '$11,000',
    thailand: '$13,000',
    usa: '$45,000',
    savings: '65% – 90%',
  },
  {
    procedure: 'Total Hip Replacement',
    category: 'Orthopedics',
    india: '$4,800',
    singapore: '$28,000',
    malaysia: '$12,500',
    thailand: '$14,500',
    usa: '$50,000',
    savings: '65% – 90%',
  },
  {
    procedure: 'Brain Tumor Craniotomy',
    category: 'Neuro',
    india: '$6,000',
    singapore: '$48,000',
    malaysia: '$20,000',
    thailand: '$24,000',
    usa: '$140,000',
    savings: '70% – 94%',
  },
  {
    procedure: 'CAR T-cell Therapy (NexCAR19)',
    category: 'Oncology',
    india: '$45,000',
    singapore: '$380,000',
    malaysia: 'Not Available',
    thailand: 'Not Available',
    usa: '$475,000',
    savings: '85% – 90%',
  },
  {
    procedure: 'Comprehensive Cancer Therapy (Chemo + Radiation)',
    category: 'Oncology',
    india: '$4,000',
    singapore: '$35,000',
    malaysia: '$14,000',
    thailand: '$16,500',
    usa: '$80,000',
    savings: '70% – 93%',
  },
  {
    procedure: 'IVF (Per Cycle with ICSI)',
    category: 'Fertility',
    india: '$2,800',
    singapore: '$14,000',
    malaysia: '$7,000',
    thailand: '$8,500',
    usa: '$22,000',
    savings: '60% – 85%',
  },
  {
    procedure: 'Laparoscopic Gastric Sleeve (Bariatric)',
    category: 'Specialized',
    india: '$4,500',
    singapore: '$24,000',
    malaysia: '$11,500',
    thailand: '$13,000',
    usa: '$32,000',
    savings: '65% – 85%',
  },
  {
    procedure: 'All-on-4 Dental Implants (Per Arch)',
    category: 'Specialized',
    india: '$3,200',
    singapore: '$18,000',
    malaysia: '$8,000',
    thailand: '$9,500',
    usa: '$28,000',
    savings: '65% – 88%',
  },
];
